services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/var/www:Z
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - krpl
        links:
            - redis:redis
            - mongo:mongo

    php:
        build:
            context: ./docker/php
        restart: always
        volumes:
            - ./:/var/www:Z
        working_dir: /var/www
        networks:
             - krpl

    db:
        image: mysql:8.0-oracle
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "1111"
            MYSQL_DATABASE: "kryptowaluty_pl"
#       volumes:
#           - ./var/docker/mysql:/var/lib/mysql:Z
        networks:
            - krpl

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: "1111"
        networks:
            - krpl

    mongo:
        image: mongo:latest
        restart: always
#       volumes:
#           - ./var/docker/mongodb:/data/db:Z
        ports:
            - 27017:27017
        networks:
            - krpl

    redis:
        image: library/redis:alpine
        restart: always
        ports:
            - 6379:6379
        networks:
            - krpl

networks:
    krpl:
